version: "3"
volumes:
  backup:
services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    command: --replSet rs0
  db:
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    container_name: db
    build:
      context: .
      dockerfile: ./apps/db/Dockerfile
    ports:
      - "1433:1433"
    restart: always
    environment:
      SA_PASSWORD: "NavTakp190!"
      ACCEPT_EULA: "Y"
    volumes:
      - backup:/backup:z
    networks:
      - app_network
  samba:
    container_name: samba
    image: dperson/samba
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: false
    tmpfs:
      - /tmp
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - backup:/backup:z
    command: '-p -s "backup;/backup;yes;no;yes;all"'
  queue:
    container_name: queue
    image: "rabbitmq:3"
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app_network
    restart: always

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network
  transceiver:
    container_name: transceiver
    build:
      context: .
      dockerfile: ./apps/transceiver/Dockerfile
    restart: always
    networks:
      - app_network
  capture:
    image: corfr/tcpdump
    network_mode: host
    volumes:
      - ./apps/capture/tcpdump_capture.sh:/tcpdump_script.sh
    depends_on:
      - rabbitmq
    command: /bin/bash -c "/tcpdump_script.sh"
  parser:
    build:
      context: .
      dockerfile: ./apps/parser/Dockerfile
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    restart: always
networks:
  app_network:
    external: true
